#!/usr/bin/env bash
# SPDX-License-Identifer: MIT
#
# grimpal - a small script aim to auto choose grimblast or grimshot by XDG_CURRENT_DESKTOP in one place
#
# homepage: https://github.com/huge-pancake/.arch
#

mkdir -p ~/Pictures/
mkdir -p ~/Pictures/Screenshots/

args=$1

if [ XDG_CURRENT_DESKTOP == "Hyprland"]; then
	grimblast $args
elif [ XDG_CURRENT_DESKTOP == "sway" ]; then
	grimshot $args
else
	grimshot $args
fi
