#!/usr/bin/env bash

file=$1
w=$2
h=$3
x=$4
y=$5

mime=$(file -Lb --mime-type "$file")

if [[ "$mime" =~ ^image ]]; then
  kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" </dev/null >/dev/tty
	exit 1
fi

if [[ "$mime" =~ ^text ]]; then
	bat --color=always --style=plain --paging=never "$file"
	exit 1
fi

printf "$mime"
