require('catppuccin').setup({
  color_overrides = {
    mocha = {
      rosewater = '#ff8389',
      flamingo = '#ff8389',
      red = '#ff8389',
      maroon = '#ff8389',
      pink = '#ff7eb6',
      mauve = '#be95ff',
      peach = '#d44a1c',
      yellow = '#ab8600',
      green = '#08bdba',
      teal = '#33b1ff',
      sky = '#33b1ff',
      sapphire = '#33b1ff',
      blue = '#78a9ff',
      lavender = '#78a9ff',
      text = '#ffffff',
      subtext1 = '#f4f4f4',
      subtext0 = '#e0e0e0',
      overlay2 = '#adadad',
      overlay1 = '#949494',
      overlay0 = '#7a7a7a',
      surface2 = '#4f4f4f',
      surface1 = '#383838',
      surface0 = '#2e2e2e',
      base = '#161616',
      mantle = '#0d0d0d',
      crust = '#000000',
    },
  },
  styles = {
    comments = { 'italic' },
    conditionals = { 'italic' },
    functions = { 'italic' },
    keywords = { 'italic' },
    numbers = { 'bold' },
    types = { 'bold' },
  },
  integrations = {
    treesitter = true,
    native_lsp = {
      enabled = true,
      virtual_text = {
        errors = { 'italic' },
        hints = { 'italic' },
        warnings = { 'italic' },
        information = { 'italic' },
      },
      underlines = {
        errors = { 'undercurl' },
        hints = { 'undercurl' },
        warnings = { 'undercurl' },
        information = { 'undercurl' },
      },
    },

    alpha = false,
    dap = false,
    dap_ui = false,
    dashboard = false,
    fidget = false,
    flash = false,
    illuminate = { enabled = false },
    mini = { enabled = false },
    neogit = false,
    nvimtree = false,
    rainbow_delimiters = false,
    ufo = false,

    beacon = true,
    cmp = true,
    dropbar = { enabled = true, color_mode = true },
    gitsigns = true,
    headlines = true,
    hop = true,
    indent_blankline = { enabled = true, scope_color = 'surface1' },
    markdown = true,
    noice = true,
    semantic_tokens = true,
    telescope = { enabled = true, style = 'nvchad' },
  },
  highlight_overrides = {
    all = function(cp)
      return {
        NormalFloat = { bg = cp.mantle },
        FloatBorder = { bg = cp.mantle, fg = cp.mantle },
        FloatTitle = { bg = cp.mantle, fg = cp.mantle },
        CursorLineNr = { fg = cp.mauve, style = { 'bold' } },
        VertSplit = { fg = cp.surface0 },
        WinSeparator = { fg = cp.surface0 },
        Pmenu = { bg = cp.mantle },
        PmenuSbar = { bg = cp.crust },
        PmenuSel = { bg = cp.surface0, fg = '' },
        PmenuThumb = { bg = cp.surface0 },

        CmpGhostText = { link = 'Comment' },
        LspInfoBorder = { link = 'FloatBorder' },
        GitSignsChange = { fg = cp.peach },
        GitSignsCurrentLineBlame = { link = 'Comment' },

        TelescopePreviewBorder = { bg = cp.crust, fg = cp.crust },
        TelescopePreviewNormal = { bg = cp.crust },
        TelescopePreviewTitle = { fg = cp.crust, bg = cp.crust },
        TelescopePromptBorder = { bg = cp.surface0, fg = cp.surface0 },
        TelescopePromptCounter = { fg = cp.mauve, style = { 'bold' } },
        TelescopePromptNormal = { bg = cp.surface0 },
        TelescopePromptPrefix = { bg = cp.surface0 },
        TelescopePromptTitle = { fg = cp.surface0, bg = cp.surface0 },
        TelescopeResultsBorder = { bg = cp.mantle, fg = cp.mantle },
        TelescopeResultsNormal = { bg = cp.mantle },
        TelescopeResultsTitle = { fg = cp.mantle, bg = cp.mantle },
        TelescopeSelection = { bg = cp.surface0 },

        StatuslineModeNormal = { bg = cp.lavender, fg = cp.base },
        StatuslineModeInsert = { bg = cp.mauve, fg = cp.base },
        StatuslineModeVisual = { bg = cp.mauve, fg = cp.base },
        StatuslineModeReplace = { bg = cp.peach, fg = cp.base },
        StatuslineModeCommand = { bg = cp.green, fg = cp.base },
        StatuslineModeOther = { bg = cp.red, fg = cp.base },
        StatuslineDevinfo = { bg = cp.surface0, fg = cp.overlay2 },
        StatuslineFilename = { bg = cp.mantle, fg = cp.overlay2 },
        StatuslineFileinfo = { bg = cp.mantle, fg = cp.overlay2 },

        -- oxocarbon
        Structure = { fg = cp.pink },
        StorageClass = { fg = cp.pink },
        Type = { fg = cp.pink, style = { 'bold' } },
        Constant = { fg = cp.text, style = { 'bold' } },
        Number = { fg = cp.text },
        Float = { fg = cp.text },
        Boolean = { fg = cp.pink },
        ['@function.builtin'] = { fg = cp.pink },
        ['@method'] = { fg = cp.pink },
        ['@constant'] = { fg = cp.text, style = { 'bold' } },
        ['@variable.builtin'] = { fg = cp.pink },
        ['@type.builtin'] = { fg = cp.pink, style = { 'bold' } },
        ['@tag.attribute.tsx'] = { fg = cp.mauve, style = { 'italic' } },
      }
    end,
  },
})
