require('catppuccin').setup({
  styles = {
    comments = { 'italic' },
    conditionals = { 'italic' },
    functions = { 'italic' },
    keywords = { 'italic' },
    numbers = { 'bold' },
    types = { 'bold' },
  },
  default_integrations = false,
  integrations = {
    treesitter = true,
    native_lsp = {
      enabled = true,
      virtual_text = {
        errors = { 'italic' },
        hints = { 'italic' },
        warnings = { 'italic' },
        information = { 'italic' },
      },
      underlines = {
        errors = { 'undercurl' },
        hints = { 'undercurl' },
        warnings = { 'undercurl' },
        information = { 'undercurl' },
      },
      inlay_hints = {
        background = true,
      },
    },

    beacon = true,
    cmp = true,
    fidget = true,
    gitsigns = true,
    headlines = true,
    hop = true,
    markdown = true,
    mini = { enabled = true },
    semantic_tokens = true,
    telescope = { enabled = true, style = 'nvchad' },
  },
  highlight_overrides = {
    all = function(cp)
      return {
        NormalFloat = { bg = cp.mantle },
        FloatBorder = { bg = cp.mantle, fg = cp.surface2 },
        FloatTitle = { bg = cp.mantle, fg = cp.subtext0 },
        CursorLineNr = { fg = cp.mauve, style = { 'bold' } },
        PmenuSel = { bg = cp.surface0, fg = '' },
        Pmenu = { bg = cp.mantle },
        PmenuSbar = { bg = cp.crust },
        PmenuThumb = { bg = cp.surface0 },
        WinSeparator = { fg = cp.surface2 },

        VisualWhitespace = { bg = cp.surface1, fg = cp.surface2 },

        CmpItemKindSnippet = { bg = cp.mauve, fg = cp.base },
        CmpItemKindKeyword = { bg = cp.red, fg = cp.base },
        CmpItemKindText = { bg = cp.teal, fg = cp.base },
        CmpItemKindMethod = { bg = cp.blue, fg = cp.base },
        CmpItemKindConstructor = { bg = cp.blue, fg = cp.base },
        CmpItemKindFunction = { bg = cp.blue, fg = cp.base },
        CmpItemKindFolder = { bg = cp.blue, fg = cp.base },
        CmpItemKindModule = { bg = cp.blue, fg = cp.base },
        CmpItemKindConstant = { bg = cp.peach, fg = cp.base },
        CmpItemKindField = { bg = cp.green, fg = cp.base },
        CmpItemKindProperty = { bg = cp.green, fg = cp.base },
        CmpItemKindEnum = { bg = cp.green, fg = cp.base },
        CmpItemKindUnit = { bg = cp.green, fg = cp.base },
        CmpItemKindClass = { bg = cp.yellow, fg = cp.base },
        CmpItemKindVariable = { bg = cp.flamingo, fg = cp.base },
        CmpItemKindFile = { bg = cp.blue, fg = cp.base },
        CmpItemKindInterface = { bg = cp.yellow, fg = cp.base },
        CmpItemKindColor = { bg = cp.red, fg = cp.base },
        CmpItemKindReference = { bg = cp.red, fg = cp.base },
        CmpItemKindEnumMember = { bg = cp.red, fg = cp.base },
        CmpItemKindStruct = { bg = cp.blue, fg = cp.base },
        CmpItemKindValue = { bg = cp.peach, fg = cp.base },
        CmpItemKindEvent = { bg = cp.blue, fg = cp.base },
        CmpItemKindOperator = { bg = cp.blue, fg = cp.base },
        CmpItemKindTypeParameter = { bg = cp.blue, fg = cp.base },
        CmpItemKindCopilot = { bg = cp.teal, fg = cp.base },
        CmpGhostText = { link = 'Comment' },

        LspInfoBorder = { link = 'FloatBorder' },

        GitSignsChange = { fg = cp.peach },
        GitSignsCurrentLineBlame = { link = 'Comment' },

        TelescopeSelection = { bg = cp.surface0 },
        TelescopePromptCounter = { fg = cp.mauve, style = { 'bold' } },

        TelescopePromptPrefix = { bg = cp.surface0 },
        TelescopePromptNormal = { bg = cp.surface0 },
        TelescopeResultsNormal = { bg = cp.mantle },
        TelescopePreviewNormal = { bg = cp.crust },

        TelescopePromptBorder = { bg = cp.surface0, fg = cp.surface0 },
        TelescopeResultsBorder = { bg = cp.mantle, fg = cp.mantle },
        TelescopePreviewBorder = { bg = cp.crust, fg = cp.crust },
        TelescopePreviewMessage = { fg = cp.teal, style = { 'italic' } },

        TelescopePromptTitle = { fg = cp.surface0, bg = cp.surface0 },
        TelescopeResultsTitle = { fg = cp.mantle, bg = cp.mantle },
        TelescopePreviewTitle = { fg = cp.crust, bg = cp.crust },
      }
    end,
  },
})
