vim.g.settings = {
  number = 'normal',
  scrolloff = 5,
  editor = {
    tab_size = 2,
  },
  git = {
    display_blame = true,
  },
  indent_guides = {
    render = true,
    character = '▏',
  },
  lsp = {
    auto_format = true,
    display_inlay_hints = true,
  },
  modules = {
    all = {
      'lib',
      'treesitter',
      'editing',
      'themes',
      'lsp',
      'completion',
      'tools',
      'ui',
      'markdown',
    },
    vscode = { 'lib', 'treesitter', 'editing' },
  },
  ui = {
    border = 'single',
    border_preview = 'solid',
    border_input = 'rounded',
    display_fold = false,
    theme = 'catppuccin',
  },
}

-- stylua: ignore start
local icons_nerd        = {
  diagnostics           = {
    DiagnosticSignError = '󰅚 ',
    DiagnosticSignHint  = '󰌶 ',
    DiagnosticSignInfo  = '󰋽 ',
    DiagnosticSignOk    = '󰄬 ',
    DiagnosticSignWarn  = '󰀪 ',
  },
  kinds                 = {
    Array               = '󰅪 ',
    Boolean             = ' ',
    BreakStatement      = '󰙧 ',
    Call                = '󰃷 ',
    CaseStatement       = '󱃙 ',
    Class               = ' ',
    Color               = '󰏘 ',
    Constant            = '󰏿 ',
    Constructor         = '󰒓 ',
    ContinueStatement   = '→ ',
    Declaration         = '󰙠 ',
    Delete              = '󰩺 ',
    DoStatement         = '󰑖 ',
    Enum                = ' ',
    EnumMember          = ' ',
    Event               = ' ',
    Field               = ' ',
    File                = '󰈔 ',
    Folder              = '󰉋 ',
    ForStatement        = '󰑖 ',
    Format              = '󰗈 ',
    Function            = '󰊕 ',
    H1Marker            = '󰉫 ',
    H2Marker            = '󰉬 ',
    H3Marker            = '󰉭 ',
    H4Marker            = '󰉮 ',
    H5Marker            = '󰉯 ',
    H6Marker            = '󰉰 ',
    Identifier          = '󰀫 ',
    IfStatement         = '󰇉 ',
    Interface           = ' ',
    Keyboard            = '󰥻 ',
    Keyword             = '󰌋 ',
    List                = '󰅪 ',
    Log                 = '󰦪 ',
    Lsp                 = ' ',
    Macro               = '󰁌 ',
    MarkdownH1          = '󰉫 ',
    MarkdownH2          = '󰉬 ',
    MarkdownH3          = '󰉭 ',
    MarkdownH4          = '󰉮 ',
    MarkdownH5          = '󰉯 ',
    MarkdownH6          = '󰉰 ',
    Method              = '󰆧 ',
    Module              = '󰏗 ',
    Namespace           = '󰅩 ',
    Null                = '󰢤 ',
    Number              = '󰎠 ',
    Object              = '󰅩 ',
    Operator            = '󰆕 ',
    Package             = '󰆦 ',
    Pair                = '󰅪 ',
    Property            = ' ',
    Reference           = '󰦾 ',
    Regex               = ' ',
    Repeat              = '󰑖 ',
    Scope               = '󰅩 ',
    Snippet             = '󰩫 ',
    Specifier           = '󰦪 ',
    Statement           = '󰅩 ',
    String              = '󰉾 ',
    Struct              = ' ',
    SwitchStatement     = '󰺟 ',
    Terminal            = ' ',
    Text                = ' ',
    Type                = ' ',
    TypeParameter       = '󰆩 ',
    Unit                = ' ',
    Value               = '󰎠 ',
    Variable            = '󰀫 ',
    WhileStatement      = '󰑖 ',
  },
  ft                    = {
    Config              = '󰒓 ',
    Lua                 = ' ',
  },
  ui                    = {
    AngleDown           = ' ',
    AngleLeft           = ' ',
    AngleRight          = ' ',
    AngleUp             = ' ',
    ArrowDown           = '↓ ',
    ArrowLeft           = '← ',
    ArrowRight          = '→ ',
    ArrowUp             = '↑ ',
    Branch              = ' ',
    Calculator          = '󰃬 ',
    CircleFilled        = '● ',
    CircleOutline       = '○ ',
    Cmd                 = '󰞷 ',
    Cross               = '󰅖 ',
    Ok                  = '󰄬 ',
    Diamond             = '◆ ',
    Dot                 = '• ',
    DotLarge            = ' ',
    Ellipsis            = '… ',
    GitSignAdd          = '▍ ',
    GitSignChange       = '▍ ',
    GitSignChangedelete = '▍ ',
    GitSignDelete       = '▁ ',
    GitSignTopdelete    = '▔ ',
    GitSignUntracked    = '▍ ',
    Help                = '󰘥 ',
    Lazy                = '󰒲 ',
    Magnify             = '󰍉 ',
    Neovim              = ' ',
    Pin                 = '󰐃 ',
    Play                = '󰼛 ',
    TriangleDown        = '▼ ',
    TriangleLeft        = '◀ ',
    TriangleRight       = '▶ ',
    TriangleUp          = '▲ ',
  },
}
local icons_ascii       = {
  diagnostics           = {
    DiagnosticSignError = 'E ',
    DiagnosticSignHint  = 'H ',
    DiagnosticSignInfo  = 'I ',
    DiagnosticSignOk    = 'O ',
    DiagnosticSignWarn  = 'W ',
  },
  kinds                 = {
    Array               = 'A ',
    Boolean             = 'B ',
    BreakStatement      = 'B ',
    Call                = 'C ',
    CaseStatement       = 'C ',
    Class               = 'C ',
    Color               = 'C ',
    Constant            = 'C ',
    Constructor         = 'C ',
    ContinueStatement   = '→ ',
    Declaration         = 'D ',
    Delete              = 'X ',
    DoStatement         = 'D ',
    Enum                = 'E ',
    EnumMember          = 'E ',
    Event               = 'E ',
    Field               = 'F ',
    File                = 'F ',
    Folder              = 'D ',
    ForStatement        = 'F ',
    Format              = 'F ',
    Function            = 'F ',
    H1Marker            = '1 ',
    H2Marker            = '2 ',
    H3Marker            = '3 ',
    H4Marker            = '4 ',
    H5Marker            = '5 ',
    H6Marker            = '6 ',
    Identifier          = 'I ',
    IfStatement         = '? ',
    Interface           = 'I ',
    Keyboard            = 'K ',
    Keyword             = 'K ',
    List                = 'L ',
    Log                 = 'L ',
    Lsp                 = 'L ',
    Macro               = '# ',
    MarkdownH1          = '1 ',
    MarkdownH2          = '2 ',
    MarkdownH3          = '3 ',
    MarkdownH4          = '4 ',
    MarkdownH5          = '5 ',
    MarkdownH6          = '6 ',
    Method              = 'M ',
    Module              = 'M ',
    Namespace           = 'N ',
    Null                = 'N ',
    Number              = 'N ',
    Object              = 'O ',
    Operator            = 'O ',
    Package             = 'P ',
    Pair                = 'P ',
    Property            = '+ ',
    Reference           = 'R ',
    Regex               = 'R ',
    Repeat              = 'R ',
    Scope               = 'S ',
    Snippet             = 'S ',
    Specifier           = 'S ',
    Statement           = 'S ',
    String              = 'S ',
    Struct              = 'S ',
    SwitchStatement     = 'S ',
    Terminal            = 'T ',
    Text                = 'T ',
    Type                = 'T ',
    TypeParameter       = 'T ',
    Unit                = 'U ',
    Value               = 'V ',
    Variable            = 'V ',
    WhileStatement      = 'W ',
  },
  ft                    = {
    Config              = 'C ',
    Lua                 = 'L ',
  },
  ui                    = {
    AngleDown           = 'v ',
    AngleLeft           = '< ',
    AngleRight          = '> ',
    AngleUp             = '^ ',
    ArrowDown           = '↓ ',
    ArrowLeft           = '← ',
    ArrowRight          = '→ ',
    ArrowUp             = '↑ ',
    Branch              = 'G ',
    Calculator          = 'C ',
    CircleFilled        = '• ',
    CircleOutline       = '○ ',
    Cmd                 = '> ',
    Cross               = 'x ',
    Ok                  = 'v ',
    Diamond             = '◆ ',
    Dot                 = '• ',
    DotLarge            = '• ',
    Ellipsis            = '. ',
    GitSignAdd          = '+ ',
    GitSignChange       = '~ ',
    GitSignChangedelete = '= ',
    GitSignDelete       = '- ',
    GitSignTopdelete    = '- ',
    GitSignUntracked    = '+ ',
    Help                = '? ',
    Lazy                = 'Z ',
    Magnify             = 'Q ',
    Neovim              = 'N ',
    Pin                 = '* ',
    Play                = '> ',
    TriangleDown        = '▼ ',
    TriangleLeft        = '◀ ',
    TriangleRight       = '▶ ',
    TriangleUp          = '▲ ',
  },
}
-- stylua: ignore end

vim.g.icons = vim.g.has_gui and icons_nerd or icons_ascii
